version: "3"

services:
  beaconmqtt:
    image: tomdesinto/bluetooth-beacon-mqtt-exporter:rpi
    network_mode: host
    privileged: true
    environment:
      MQTT_BROKER: mqtt://127.0.0.1
      MQTT_TOPIC: beacon
      MQTT_RECONNECT_DELAY: 5000
      LOG_PACKETS: "yes"
